- name: Creates App directory
  shell: |
    mkdir -p ~/app

- name: copying file with playbook
  copy:
    src: ../../artifact.tar.gz
    dest: ~/app

- name: Install dependencies
  shell: |
    cd /home/ubuntu/app
    tar xf /home/ubuntu/app/artifact.tar.gz

- name: Start backend
  shell: |
    /usr/bin/pm2 start /home/ubuntu/app/dist/main.js --name backend -f
  environment:
    ENVIRONMENT: production
    NODE_ENV: production
