- name: copying file with playbook
  become: true
  copy:
    src: ../../artifact.tar.gz
    dest: ~/

- name: Executing node
  shell: |
    cd ../../
    tar -zxvf artifact.tar.gz    
    npm install
    pm2 stop default
    pm2 start npm -- start
