- name: Creates App directory
  file:
    path: ~/app
    state: directory

- name: copying file with playbook
  become: true
  copy:
    src: ../../artifact.tar.gz
    dest: ~/app

- name: Install dependencies
  become: true
  shell: |
    cd /home/ubuntu/app
    tar xf /home/ubuntu/app/artifact.tar.gz

- name: Start backend
  shell: |
    /usr/bin/pm2 start /home/ubuntu/app/dist/main.js --name backend -f
  environment:
    ENVIRONMENT: production
    NODE_ENV: production
